@startuml
title 《Overwall后台管理系统》-用例分析

actor 用户
actor 管理员

package 捐赠系统{
用户 -up->(发起捐赠)
用户 -up->(查看捐赠记录)
管理员 -up->(捐赠审批)
}

package 用户和服务器信息系统{
用户 -down->(用户注册)
用户 -down->(获取服务器信息)
用户 -down->(获取用户信息)
管理员 -down->(用户管理)
管理员 ->(服务器管理)
管理员 ->(系统设置)
}
@enduml